export const GET_MEDICINES = "GET_MEDICINES"
export const ADD_MEDICINES = "ADD_MEDICINES"
export const DELETE_MEDICINES = "DELETE_MEDICINES"
export const UPDATE_MEDICINES = "UPDATE_MEDICINES"

export const GET_DOCTOR = "GET_DOCTOR"
export const ADD_DOCTOR = "ADD_DOCTOR"
export const DELETE_DOCTOR = "DELETE_DOCTOR"
export const UPDATE_DOCTOR = "UPDATE_DOCTOR"

export const LOADING = "LOADING"
export const ERROR = "ERROR"